
name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: steve9II/alioss-deploy-action@v1.0-beta
        with:
          region: oss-cn-hangzhou.aliyuncs.com
          accessKeyId: ${{secrets.ACCESS_ID}}
          accessKeySecret: ${{secrets.ACCESS_KEY_SECRET}}
          bucket: ${{secrets.BUCKET}}
          staticPath: .
          deployPath: /models/